Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.10"

    # Provisionamiento: ejecutar el script que instala Nginx y copia el sitio
    web.vm.provision "shell", path: "scripts/instalar_nginx.sh"

    # Opcional: asignar recursos
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
